all: 5_calor_explicito_fuerza_externa

5_calor_explicito_fuerza_externa: 5_calor_explicito_fuerza_externa.c aan_calor_explicito_fuerza_externa.c aan_calor_explicito_fuerza_externa.h float_utils.c float_utils.h
	gcc -Wall -lm -g 5_calor_explicito_fuerza_externa.c aan_calor_explicito_fuerza_externa.c float_utils.c -o 5_calor_explicito_fuerza_externa

clean:
	rm -rf 5_calor_explicito_fuerza_externa
