2_mascara: 2_mascara.c \
           float_utils.c float_utils.h \
           aan_normalizar.c aan_normalizar.h \
           aan_mascara.c aan_mascara.h \
           aan_unir_canales.c aan_unir_canales.h \
           ami.h ami_bmp.h
	gcc -Wall -lm -g 2_mascara.c float_utils.c aan_normalizar.c aan_mascara.c aan_unir_canales.c -o 2_mascara
	
clean:
	rm -rf *bmp 2_mascara
