all: 31_bef0 32_dt1

31_bef0: lotka_volterra.h lotka_volterra.c 31_bef0.c
	gcc -g 31_bef0.c lotka_volterra.c -o 31_bef0
	
32_dt1: 32_dt1.c lotka_volterra.h lotka_volterra.c
	gcc -g 32_dt1.c lotka_volterra.c -o 32_dt1
	
#33_equilibrio:

#34_extincion:
