all: 9_perona_malik

9_perona_malik: 9_perona_malik.c float_utils.c aan_mascara.c float_utils.h aan_mascara.h ami.h ami_bmp.h aan_perona_malik.c aan_perona_malik.h
	gcc -lm -o 9_perona_malik -g 9_perona_malik.c float_utils.c aan_mascara.c aan_perona_malik.c 

clean:
	rm -rf 9_perona_malik
